"""
Django settings for marketplace project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from datetime import timedelta

import firebase_admin
from firebase_admin import credentials
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta

import firebase_admin
from firebase_admin import credentials
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ASGI_APPLICATION = "marketplace.asgi.application"

def _get_bool_env(key: str, default: bool = False) -> bool:
    return os.getenv(key, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def _get_required_env(key: str) -> str:
    value = os.getenv(key)
    if value is None or value.strip() == "":
        raise ImproperlyConfigured(f"Missing required environment variable: {key}")
    return value


ENV = os.getenv("ENV", "dev").strip().lower()
if ENV not in {"dev", "staging", "prod"}:
    raise ImproperlyConfigured(f"Invalid ENV: {ENV}")

env_file = BASE_DIR / ".env"
# For local/staging convenience, load .env file if it exists.
if ENV in {"dev", "staging"} and env_file.exists():
    load_dotenv(env_file, override=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY is required")
if ENV == "prod" and SECRET_KEY == 'django-insecure-unsafe-dev-key':
    raise ImproperlyConfigured("SECRET_KEY must be set in production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool_env('DEBUG', ENV != 'prod')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,10.0.2.2').split(',') if h.strip()]
if ENV == "prod" and (not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS):
    raise ImproperlyConfigured("Set ALLOWED_HOSTS to your EC2 domain/IP in production")

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
AUTH_ACCESS_TOKEN_EXPIRES_IN = int(os.getenv("AUTH_ACCESS_TOKEN_EXPIRES_IN", "15"))       # minutes
AUTH_REFRESH_TOKEN_EXPIRES_IN = int(os.getenv("AUTH_REFRESH_TOKEN_EXPIRES_IN", "43200"))  # minutes — default 30 days
AUTH_JWT_ALGORITHM = os.getenv("AUTH_JWT_ALGORITHM", "HS256")
AUTH_JWT_SECRET = os.getenv("AUTH_JWT_SECRET", SECRET_KEY)
AUTH_REFRESH_TOKEN_PEPPER = os.getenv("AUTH_REFRESH_TOKEN_PEPPER", SECRET_KEY)
RESET_PASSWORD_EXPIRES_IN_MINUTES = int(
    os.getenv("RESET_PASSWORD_EXPIRES_IN_MINUTES", "15")
)

# OTP expiry per purpose (minutes). Falls back to RESET_PASSWORD_EXPIRES_IN_MINUTES.

OTP_EXPIRY_MINUTES = {
    "WITHDRAW_VERIFY": int(os.getenv("OTP_WITHDRAW_EXPIRE_MINUTES", 2)),
    "BANK_VERIFY": int(os.getenv("OTP_BANK_EXPIRE_MINUTES", 2)),
    "SIGNUP": int(os.getenv("OTP_SIGNUP_EXPIRE_MINUTES", 15)),
    "RESET_PASSWORD": int(os.getenv("OTP_RESET_PASSWORD_EXPIRE_MINUTES", 15)),
}

WALLET_CHAIN_SECRET = os.getenv("WALLET_CHAIN_SECRET", "")
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'ninja_extra',
    'corsheaders',
    'rest_framework',
    'admin',  # Admin dashboard app
    'users',
    'attachment',
    'dish',
    'ingredient',
    'menu',
    'profile',
    'cart',
    'order',
    'payment',
    'voucher',
    'certificate',
    'review',
    'recommendation',
    'channels', 
    'chat',
    'mongo_chat',
    'django_dbml',
    'tracking',
    'verification',
    'report',
]

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME", "amomeal_chat")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add for static files
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketplace.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates", BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = 'marketplace.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL from Render, fallback to local config
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": os.environ.get("POSTGRES_HOST"),
            "PORT": os.environ.get("POSTGRES_PORT"),
        }
    }


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'chat.authentication.PureJWTAuthentication',
    ),
    
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

CORS_ALLOW_ALL_ORIGINS = _get_bool_env('CORS_ALLOW_ALL_ORIGINS', DEBUG)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Password hashing
# Argon2id is the OWASP-recommended, memory-hard algorithm (PHC winner 2015).
# argon2-cffi is already installed (used for OTP hashing).
# Django will transparently upgrade existing PBKDF2 hashes to Argon2id on next login.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",   # primary — new passwords
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",   # fallback — existing passwords
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sent email
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))
FRONTEND_URL = os.getenv("FRONTEND_URL")

AUTH_USER_MODEL = "users.CustomUser"

# AI model integration
AI_MODEL_BASE_URL = os.getenv("AI_MODEL_BASE_URL", "http://localhost:8001")
AI_MODEL_TIMEOUT_SECONDS = int(os.getenv("AI_MODEL_TIMEOUT_SECONDS", "10"))

#Gemini API integration (optional): used by daily nutrition meal parser.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# OpenAI integration (optional): used by daily nutrition meal parser.
# OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
# OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
# OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")

# Ollama / local LLM integration (preferred for meal parsing)
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama-3.1")

# Recommendation engine config
RECOMMENDATION_CONFIG = {
    "candidate_pool_size": int(os.getenv("RECOMMENDATION_CANDIDATE_POOL_SIZE", "300")),
    "candidate_max_per_category": int(os.getenv("RECOMMENDATION_CANDIDATE_MAX_PER_CATEGORY", "0")),
    "use_pgvector_ann_candidates": _get_bool_env("RECOMMENDATION_USE_PGVECTOR_ANN_CANDIDATES", False),
    "history_decay_lambda": float(os.getenv("RECOMMENDATION_HISTORY_DECAY_LAMBDA", "0.03")),
    "recency_decay_lambda": float(os.getenv("RECOMMENDATION_RECENCY_DECAY_LAMBDA", "0.02")),
    "favorite_recency_decay_lambda": float(
        os.getenv("RECOMMENDATION_FAVORITE_RECENCY_DECAY_LAMBDA", "0.03")
    ),
    "user_vector_ema_alpha": float(os.getenv("RECOMMENDATION_USER_VECTOR_EMA_ALPHA", "0.35")),
    "diet_balanced_target": [
        float(os.getenv("RECOMMENDATION_DIET_BALANCED_TARGET_PROTEIN", "0.3")),
        float(os.getenv("RECOMMENDATION_DIET_BALANCED_TARGET_FAT", "0.3")),
        float(os.getenv("RECOMMENDATION_DIET_BALANCED_TARGET_CARB", "0.4")),
    ],
    "mmr_lambda": float(os.getenv("RECOMMENDATION_MMR_LAMBDA", "0.5")),
    "use_pgvector_similarity": _get_bool_env("RECOMMENDATION_USE_PGVECTOR_SIMILARITY", False),
    "penalty_gamma": float(os.getenv("RECOMMENDATION_PENALTY_GAMMA", "0.25")),
    "penalty_correlation_threshold": float(
        os.getenv("RECOMMENDATION_PENALTY_CORRELATION_THRESHOLD", "0.35")
    ),
    "weights": {
        "w1": float(os.getenv("RECOMMENDATION_W1", "0.4")),
        "w2": float(os.getenv("RECOMMENDATION_W2", "0.2")),
        "w3": float(os.getenv("RECOMMENDATION_W3", "0.2")),
        "w4": float(os.getenv("RECOMMENDATION_W4", "0.1")),
        "w5": float(os.getenv("RECOMMENDATION_W5", "0.1")),
    },
}

# S3 Configuration
USE_S3 = os.getenv('USE_S3', 'False') == 'True'

if USE_S3:
    # S3 settings (primary interface)
    S3_ACCESS_KEY_ID = os.getenv('S3_ACCESS_KEY_ID')
    S3_SECRET_ACCESS_KEY = os.getenv('S3_SECRET_ACCESS_KEY')
    S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME')
    S3_REGION = os.getenv('S3_REGION')
    S3_PUBLIC_URL = os.getenv('S3_PUBLIC_URL')
    S3_EXPIRES_IN = int(os.getenv('S3_EXPIRES_IN', '3600'))
    
    # Django Storages configuration (requires AWS_* naming internally)
    AWS_ACCESS_KEY_ID = S3_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = S3_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = S3_BUCKET_NAME
    AWS_S3_REGION_NAME = S3_REGION
    AWS_S3_CUSTOM_DOMAIN = f'{S3_BUCKET_NAME}.s3.{S3_REGION}.amazonaws.com'
    
    # S3 file storage settings
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_QUERYSTRING_AUTH = False
    
    # Media files (uploads)
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
else:
    # Local file storage
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    
    # S3 settings (disabled)
    S3_ACCESS_KEY_ID = None
    S3_SECRET_ACCESS_KEY = None
    S3_BUCKET_NAME = None
    S3_REGION = None
    S3_PUBLIC_URL = None
    S3_EXPIRES_IN = 3600

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    
# Redis
# DB 0 — Channel Layers (WebSocket pub/sub)
# DB 1 — Refresh token store  (rt:token:* and rt:user:*)
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))

# Full URL used by users/redis_tokens.py  (DB 1 keeps tokens isolated from channels)
REDIS_URL = os.getenv("REDIS_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/1")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # DB 0 for Channel Layers
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}
    