# Generated by Django 5.2.1 on 2026-01-20 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('available_date',),
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('name_no_accent', models.TextField(blank=True, editable=False)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('BEVERAGES', 'Beverages'), ('DESSERT', 'Dessert')], max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of Stock')], default='AVAILABLE', max_length=16)),
                ('deleted', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='portion_docs/')),
                ('attachment', models.ForeignKey(blank=True, db_column='attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_fk_attachment', to='attachment.attachment')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
