# Generated by Django 5.2.1 on 2026-01-20 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        ('ingredient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_fk_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='updater',
            field=models.ForeignKey(blank=True, db_column='updater_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_fk_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dishavailability',
            name='dish',
            field=models.ForeignKey(db_column='dish_uid', on_delete=django.db.models.deletion.CASCADE, related_name='availability_fk_dish', to='dish.dish'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(db_column='dish_uid', on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredient_fk_dish', to='dish.dish'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient_uid', on_delete=django.db.models.deletion.RESTRICT, related_name='dish_ingredient_fk_ingredient', to='ingredient.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='dishavailability',
            unique_together={('dish', 'available_date')},
        ),
        migrations.AlterUniqueTogether(
            name='dishingredient',
            unique_together={('dish', 'ingredient')},
        ),
    ]
