# Generated by Django 5.2.1 on 2026-01-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='file',
        ),
    ]
