# Generated by Django 5.2.1 on 2026-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_remove_dish_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
