# Generated by Django 5.2.1 on 2026-04-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_dish_avg_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('type', models.CharField(choices=[('region', 'Region'), ('subregion', 'Subregion'), ('country', 'Country')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dish.dishlocation')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_fk_location', to='dish.dishlocation'),
        ),
        migrations.AddIndex(
            model_name='dishlocation',
            index=models.Index(fields=['type'], name='dish_dishlo_type_b91c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='dishlocation',
            index=models.Index(fields=['parent'], name='dish_dishlo_parent__0b2133_idx'),
        ),
        migrations.AddConstraint(
            model_name='dishlocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent__isnull', True), ('type', 'region')), models.Q(('parent__isnull', False), ('type__in', ['subregion', 'country'])), _connector='OR'), name='valid_location_parent_null'),
        ),
        migrations.AlterUniqueTogether(
            name='dishlocation',
            unique_together={('name', 'parent')},
        ),
    ]
