# Generated by Django 5.2.1 on 2026-04-10

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_dishlocation_dish_location_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dishlocation',
            name='valid_location_parent_null',
        ),
        migrations.AddConstraint(
            model_name='dishlocation',
            constraint=models.CheckConstraint(
                condition=(
                    Q(type='REGION', parent_id__isnull=True)
                    | Q(type__in=['SUBREGION', 'COUNTRY'], parent_id__isnull=False)
                ),
                name='valid_location_parent_null',
            ),
        ),
    ]