# Generated by Django 5.2.1 on 2026-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_fix_dishlocation_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dishlocation',
            name='valid_location_parent_null',
        ),
        migrations.AlterField(
            model_name='dishlocation',
            name='type',
            field=models.CharField(choices=[('REGION', 'Region'), ('SUBREGION', 'Subregion'), ('COUNTRY', 'Country')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dishlocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent_id__isnull', True), ('type', 'REGION')), models.Q(('parent_id__isnull', False), ('type', 'SUBREGION')), models.Q(('parent_id__isnull', False), ('type', 'COUNTRY')), _connector='OR'), name='valid_location_parent_null'),
        ),
    ]
