# Generated by Django 5.2.1 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0007_remove_dishlocation_valid_location_parent_null_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='private_final_score',
            field=models.FloatField(default=0),
        ),
    ]
