# Generated by Django 5.2.1 on 2026-04-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0008_dish_private_final_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='private_final_score',
            new_name='final_score',
        ),
    ]
