# Generated by Django 5.2.1 on 2026-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0011_remove_dishingredient_cu_remove_dishingredient_flo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishingredient',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
