# Generated by Django 5.2.1 on 2026-04-22 13:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0012_dishingredient_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishingredient',
            name='id',
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
