# Generated by Django 5.2.1 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0013_remove_dishingredient_id_dishingredient_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishingredient",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                db_column="ingredient_uid",
                null=True,
                on_delete=models.RESTRICT,
                related_name="dish_ingredient_fk_ingredient",
                to="ingredient.ingredient",
                to_field="uid",
            ),
        ),
        migrations.AddField(
            model_name="dishingredient",
            name="custom_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dishingredient",
            name="approval_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                default="APPROVED",
                max_length=16,
            ),
        ),
    ]
