# Generated by Django 5.2.1 on 2026-04-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0014_dishingredient_custom_name_approval_status"),
        ("ingredient", "0005_ingredientsuggestion_verify_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dishingredient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dish_ingredient_fk_creator",
                to=settings.AUTH_USER_MODEL,
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="dishingredient",
            name="source",
            field=models.CharField(
                choices=[("CHEF_SUGGESTION", "Chef Suggestion"), ("USDA", "USDA Database")],
                default="USDA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dishingredient",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                db_column="suggestion_uid",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dish_ingredient_fk_suggestion",
                to="ingredient.ingredientsuggestion",
                to_field="uid",
            ),
        ),
        migrations.AddField(
            model_name="dishingredient",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dish_ingredient_fk_updater",
                to=settings.AUTH_USER_MODEL,
                to_field="id",
            ),
        ),
    ]
