# Generated by Django 5.2.1 on 2026-04-23 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0015_dishingredient_source_suggestion_audit'),
        ('ingredient', '0006_favouriteingredient_deleted_allergicingredient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_ingredient_fk_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, db_column='ingredient_uid', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dish_ingredient_fk_ingredient', to='ingredient.ingredient'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='suggestion',
            field=models.ForeignKey(blank=True, db_column='suggestion_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_ingredient_fk_suggestion', to='ingredient.ingredientsuggestion'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_ingredient_fk_updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
