# Generated by Django 5.2.1 on 2026-05-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0017_dishingredient_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.TextField()),
                ('alias_name_no_accent', models.TextField(blank=True, editable=False)),
                ('similarity_score', models.FloatField(default=0.9)),
                ('alias_type', models.CharField(choices=[('REGIONAL', 'Regional Name'), ('ABBREVIATION', 'Abbreviation'), ('TRANSLATION', 'Translation'), ('SYNONYM', 'Synonym')], default='SYNONYM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(db_column='dish_uid', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='dish.dish')),
            ],
            options={
                'indexes': [models.Index(fields=['dish'], name='dish_dishal_dish_ui_de5888_idx'), models.Index(fields=['alias_name_no_accent'], name='dish_dishal_alias_n_debd52_idx'), models.Index(fields=['alias_type'], name='dish_dishal_alias_t_60d10e_idx')],
                'unique_together': {('dish', 'alias_name_no_accent')},
            },
        ),
    ]
