# Generated by Django 5.2.1 on 2026-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0018_dishalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
