# Generated by Django 5.2.1 on 2026-06-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0019_dish_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='serving_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='Số người ăn cho 1 phần (1=cá nhân, 4=gia đình/lẩu). Dùng để chuẩn hóa dinh dưỡng per-serving.'),
        ),
    ]
