HIGH_SUGAR_KEYWORDS = {
    "strong": [
        "đường",
        "đường trắng",
        "đường nâu",
        "đường cát",
        "siro",
        "sirô",
        "mật ong",
        "sữa đặc",
        "sữa đặc có đường",
        "caramel",
        "kẹo",
        "socola",
        "chocolate",
        "mứt",
        "syrup",
    ],
    "weak": [
        "bột cacao",
        "cacao",
    ],
}

HIGH_FAT_KEYWORDS = {
    "strong": [
        "mỡ",
        "mỡ heo",
        "mỡ bò",
        "mỡ gà",
        "bơ",
        "bơ động vật",
        "bơ thực vật",
        "phô mai",
        "cheese",
        "kem béo",
        "whipping cream",
        "heavy cream",
        "dầu ăn",
        "dầu olive",
        "dầu mè",
        "dầu dừa",
        "mayonnaise",
        "lòng đỏ trứng",
        "da gà",
        "da vịt",
        "thịt mỡ",
        "ba chỉ",
        "bacon",
        "xúc xích",
        "lạp xưởng",
    ],
    "weak": [
        "chiên",
        "rán",
    ],
}

HIGH_PROTEIN_KEYWORDS = {
    "strong": [
        "thịt bò",
        "thịt heo",
        "thịt gà",
        "ức gà",
        "cá hồi",
        "cá thu",
        "cá lóc",
        "cá ngừ",
        "tôm",
        "mực",
        "hải sản",
        "trứng",
        "trứng gà",
        "trứng vịt",
        "đậu hũ",
        "đậu phụ",
        "đậu nành",
        "whey",
    ],
    "weak": [
        "đậu",
        "sữa tươi",
        "sữa chua",
        "phô mai",  # fat + protein
    ],
}

IMPORT_COLUMNS = [
    "name",
    "category",
    "weight",
    "energy",
    "protein",
    "lipid",
    "carbohydrate",
    "fiber",
    "natri",
    "kali",
    "cholesterol",
    "retinol",
    "caroten",
    "vitamin_b_1",
    "vitamin_b_2",
    "vitamin_pp",
    "vitamin_c",
    "calcium",
    "phosphorus",
    "fe",
    "mg",
    "zn",
]

DISH_NUTRIENT_FIELDS = [
    "energy",
    "protein",
    "lipid",
    "carbohydrate",
    "fiber",
    "natri",
    "kali",
    "cholesterol",
    "retinol",
    "caroten",
    "vitamin_b_1",
    "vitamin_b_2",
    "vitamin_pp",
    "vitamin_c",
    "calcium",
    "phosphorus",
    "fe",
    "mg",
    "zn",
]
