# Generated by Django 5.2.1 on 2026-01-20 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FOOD', 'Food'), ('DISH', 'Dish'), ('PORTION', 'Portion'), ('OTHER', 'Other')], default='OTHER', max_length=255)),
                ('original_name', models.TextField()),
                ('hashed_name', models.TextField()),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=255)),
                ('directory', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('public_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_file_deleted', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
