# Generated by Django 5.2.1 on 2026-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('FOOD', 'Food'), ('DISH', 'Dish'), ('PORTION', 'Portion'), ('CHEF_AVATAR', 'Chef Avatar'), ('CUSTOMER_AVATAR', 'Customer Avatar'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
