# Generated by Django 5.2.1 on 2026-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_alter_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('FOOD', 'Food'), ('DISH', 'Dish'), ('CERTIFICATE', 'Certificate'), ('CHEF_AVATAR', 'Chef Avatar'), ('CUSTOMER_AVATAR', 'Customer Avatar'), ('REVIEW', 'Review'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
