# Generated by Django 5.2.1 on 2026-04-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0006_alter_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('INGREDIENT', 'Ingredient'), ('DISH', 'Dish'), ('CERTIFICATE', 'Certificate'), ('CHEF_AVATAR', 'Chef Avatar'), ('CUSTOMER_AVATAR', 'Customer Avatar'), ('REVIEW', 'Review'), ('OTHER', 'Other'), ('CHAT', 'Chat')], default='OTHER', max_length=255),
        ),
    ]
