# Generated by Django 5.2.1 on 2026-06-03 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0007_alter_attachment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefVerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd_status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTED', 'Extracted'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=20)),
                ('cccd_extracted', models.JSONField(blank=True, null=True)),
                ('cccd_confirmed', models.JSONField(blank=True, null=True)),
                ('business_status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTED', 'Extracted'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=20)),
                ('business_extracted', models.JSONField(blank=True, null=True)),
                ('business_confirmed', models.JSONField(blank=True, null=True)),
                ('food_safety_status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTED', 'Extracted'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=20)),
                ('food_safety_extracted', models.JSONField(blank=True, null=True)),
                ('food_safety_confirmed', models.JSONField(blank=True, null=True)),
                ('cross_validation_passed', models.BooleanField(null=True)),
                ('cross_validation_errors', models.JSONField(default=list)),
                ('verification_code', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('selfie_extracted', models.JSONField(blank=True, null=True)),
                ('face_similarity_score', models.FloatField(blank=True, null=True)),
                ('risk_flags', models.JSONField(default=list)),
                ('risk_score', models.IntegerField(default=0)),
                ('decision', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('AWAITING_SELFIE', 'Awaiting Selfie'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=25)),
                ('cccd_number_masked', models.CharField(blank=True, max_length=20, null=True)),
                ('cccd_number_hash', models.TextField(blank=True, null=True)),
                ('verified_identity', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_attachment', models.ForeignKey(blank=True, db_column='business_attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attachment.attachment')),
                ('cccd_attachment', models.ForeignKey(blank=True, db_column='cccd_attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attachment.attachment')),
                ('food_safety_attachment', models.ForeignKey(blank=True, db_column='food_safety_attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attachment.attachment')),
                ('selfie_attachment', models.ForeignKey(blank=True, db_column='selfie_attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attachment.attachment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_verification_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef Verification Session',
                'verbose_name_plural': 'Chef Verification Sessions',
            },
        ),
    ]
