# Generated by Django 5.2.1 on 2026-06-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_remove_certificate_attachment_certificateattachment'),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefverificationsession',
            name='business_attachment',
        ),
        migrations.RemoveField(
            model_name='chefverificationsession',
            name='cccd_attachment',
        ),
        migrations.RemoveField(
            model_name='chefverificationsession',
            name='food_safety_attachment',
        ),
        migrations.AddField(
            model_name='chefverificationsession',
            name='business_attachment_uids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chefverificationsession',
            name='business_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificate.certificate'),
        ),
        migrations.AddField(
            model_name='chefverificationsession',
            name='cccd_attachment_uids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chefverificationsession',
            name='food_safety_attachment_uids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chefverificationsession',
            name='food_safety_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificate.certificate'),
        ),
    ]
