# Generated by Django 5.2.1 on 2026-06-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_scheduleds3deletion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduleds3deletion',
            new_name='verificatio_is_exec_42d953_idx',
            old_name='verification_sched_idx',
        ),
    ]
