# Generated by Django 5.2.1 on 2026-02-25 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_order_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Mã voucher (vd: SUMMER2024)', max_length=50)),
                ('name', models.CharField(help_text='Tên voucher', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết voucher', null=True)),
                ('voucher_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], default='PERCENTAGE', help_text='Loại giảm giá: % hoặc số tiền cố định', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Giá trị giảm (% hoặc số tiền)', max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền giảm tối đa (cho voucher %)', max_digits=12, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Giá trị đơn hàng tối thiểu để áp dụng', max_digits=12)),
                ('start_date', models.DateTimeField(help_text='Ngày bắt đầu hiệu lực')),
                ('end_date', models.DateTimeField(help_text='Ngày hết hạn')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Số lần sử dụng tối đa (null = không giới hạn)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Số lần đã sử dụng')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='Số lần mỗi user có thể dùng')),
                ('is_active', models.BooleanField(default=True, help_text='Voucher có đang hoạt động không')),
                ('chef', models.ForeignKey(db_column='chef_id', help_text='Chef tạo voucher này', on_delete=django.db.models.deletion.CASCADE, related_name='voucher_fk_chef', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voucher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Số tiền đã giảm', max_digits=12)),
                ('order', models.ForeignKey(blank=True, db_column='order_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucherusage_fk_order', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucherusage_fk_user', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(db_column='voucher_uid', on_delete=django.db.models.deletion.CASCADE, related_name='voucherusage_fk_voucher', to='voucher.voucher')),
            ],
            options={
                'db_table': 'voucher_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['chef', 'code'], name='voucher_chef_id_30ddff_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['chef', 'is_active', 'start_date', 'end_date'], name='voucher_chef_id_21fab5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('chef', 'code')},
        ),
    ]
