# Generated by Django 5.2.1 on 2026-03-03 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_voucher'),
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], default='PERCENTAGE', help_text='Loại giảm giá: % hoặc số tiền cố định', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='chef',
            field=models.ForeignKey(blank=True, db_column='chef_id', help_text='Chef tạo voucher này, dùng cho SHOP_SUBTOTAL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_fk_chef', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('SHOP_VOUCHER', 'Shop Voucher (dành cho chef tạo)'), ('PLATFORM_SUBTOTAL', 'Platform Voucher (dành cho admin tạo)'), ('PLATFORM_SHIPPING', 'Platform Shipping Voucher (dành cho admin tạo, chỉ giảm phí ship)')], help_text='Loại voucher: SHOP_VOUCHER, PLATFORM_SUBTOTAL, PLATFORM_SHIPPING', max_length=30),
        ),
        migrations.CreateModel(
            name='AppliedVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('SHOP_VOUCHER', 'Shop Voucher (dành cho chef tạo)'), ('PLATFORM_SUBTOTAL', 'Platform Voucher (dành cho admin tạo)'), ('PLATFORM_SHIPPING', 'Platform Shipping Voucher (dành cho admin tạo, chỉ giảm phí ship)')], help_text='Loại voucher: SHOP_VOUCHER, PLATFORM_SUBTOTAL, PLATFORM_SHIPPING', max_length=30)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền giảm giá thực tế', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_applied_vouchers', to='order.checkout')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_applied_vouchers', to='order.order')),
                ('user', models.ForeignKey(help_text='User đã apply voucher này', on_delete=django.db.models.deletion.CASCADE, related_name='user_applied_vouchers', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_vouchers', to='voucher.voucher')),
            ],
        ),
        migrations.DeleteModel(
            name='VoucherUsage',
        ),
        migrations.AddConstraint(
            model_name='appliedvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('voucher_type', 'SHOP_VOUCHER')), fields=('order', 'voucher_type'), name='unique_shop_voucher_per_order'),
        ),
        migrations.AddConstraint(
            model_name='appliedvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('voucher_type', 'PLATFORM_SUBTOTAL')), fields=('checkout', 'voucher_type'), name='unique_platform_subtotal_voucher_per_checkout'),
        ),
        migrations.AddConstraint(
            model_name='appliedvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('voucher_type', 'PLATFORM_SHIPPING')), fields=('checkout', 'voucher_type'), name='unique_platform_shipping_voucher_per_checkout'),
        ),
    ]
