# Generated by Django 5.2.1 on 2026-03-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_voucher_discount_type_alter_voucher_chef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedvoucher',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm hết hạn reservation (15 phút sau khi apply)', null=True),
        ),
        migrations.AddField(
            model_name='appliedvoucher',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved (pending checkout)'), ('USED', 'Used (order placed)'), ('CANCELLED', 'Cancelled (checkout cancelled)'), ('EXPIRED', 'Expired (reservation timeout)')], default='RESERVED', help_text='Trạng thái: RESERVED (giữ chỗ), USED (đã dùng), CANCELLED (hủy), EXPIRED (hết hạn)', max_length=20),
        ),
        migrations.AddField(
            model_name='appliedvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
