# Generated by Django 5.2.1 on 2026-03-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_appliedvoucher_reservation_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='usage_count',
        ),
    ]
