# Generated by Django 5.2.1 on 2026-01-20 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('name_no_accent', models.TextField(blank=True, editable=False)),
                ('category', models.CharField(choices=[('GRAIN', 'Grain'), ('PROTEIN', 'Protein'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('OILFATBUTTER', 'OilFatButter'), ('SPICE', 'Spice'), ('MILK', 'Milk')], max_length=16)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('lipid', models.FloatField(blank=True, null=True)),
                ('carbohydrate', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('natri', models.FloatField(blank=True, null=True)),
                ('kali', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('retinol', models.FloatField(blank=True, null=True)),
                ('caroten', models.FloatField(blank=True, null=True)),
                ('vitamin_b_1', models.FloatField(blank=True, null=True)),
                ('vitamin_b_2', models.FloatField(blank=True, null=True)),
                ('vitamin_pp', models.FloatField(blank=True, null=True)),
                ('vitamin_c', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('fe', models.FloatField(blank=True, null=True)),
                ('mg', models.FloatField(blank=True, null=True)),
                ('zn', models.FloatField(blank=True, null=True)),
                ('mn', models.FloatField(blank=True, null=True)),
                ('cu', models.FloatField(blank=True, null=True)),
                ('flo', models.FloatField(blank=True, null=True)),
                ('iot', models.FloatField(blank=True, null=True)),
                ('se', models.FloatField(blank=True, null=True)),
                ('total_fa', models.FloatField(blank=True, null=True)),
                ('palmitic', models.FloatField(blank=True, null=True)),
                ('stearic', models.FloatField(blank=True, null=True)),
                ('linoleic', models.FloatField(blank=True, null=True)),
                ('linolenic', models.FloatField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('attachment', models.ForeignKey(blank=True, db_column='attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_fk_attachment', to='attachment.attachment')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
