# Generated by Django 5.2.1 on 2026-01-20 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_fk_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updater',
            field=models.ForeignKey(blank=True, db_column='updater_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_fk_updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
