# Generated by Django 5.2.1 on 2026-04-21 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.TextField()),
                ('alias_no_accent', models.TextField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_alias_fk_creator', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(db_column='ingredient_uid', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ingredient.ingredient')),
            ],
            options={
                'ordering': ('alias',),
            },
        ),
        migrations.CreateModel(
            name='IngredientSuggestion',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_name', models.TextField()),
                ('suggested_name_no_accent', models.TextField(blank=True, editable=False)),
                ('suggested_category', models.CharField(blank=True, choices=[('GRAIN', 'Grain'), ('PROTEIN', 'Protein'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('OILFATBUTTER', 'OilFatButter'), ('SPICE', 'Spice'), ('MILK', 'Milk')], max_length=16, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_suggestion_fk_creator', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(blank=True, db_column='ingredient_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_suggestion_fk_resolved_ingredient', to='ingredient.ingredient')),
                ('resolved_alias', models.ForeignKey(blank=True, db_column='resolved_alias_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_suggestion_fk_resolved_alias', to='ingredient.ingredientalias')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FavouriteIngredient',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_uid', on_delete=django.db.models.deletion.CASCADE, related_name='favourite_ingredient_fk_ingredient', to='ingredient.ingredient')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favourite_ingredient_fk_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ingredient', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='ingredientalias',
            constraint=models.UniqueConstraint(fields=('alias_no_accent',), name='unique_ingredient_alias_no_accent'),
        ),
    ]
