# Generated by Django 5.2.1 on 2026-04-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_ingredientalias_ingredientsuggestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='cu',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='flo',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='iot',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='linoleic',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='linolenic',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='mn',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='palmitic',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='se',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='stearic',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='total_fa',
        ),
    ]
