# Generated by Django 5.2.1 on 2026-04-23 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_ingredientsuggestion_verify_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteingredient',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AllergicIngredient',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(db_column='ingredient_uid', on_delete=django.db.models.deletion.CASCADE, related_name='allergic_ingredient_fk_ingredient', to='ingredient.ingredient')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='allergic_ingredient_fk_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ingredient', 'user')},
            },
        ),
    ]
