# Generated by Django 5.2.1 on 2026-04-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0006_alter_attachment_type'),
        ('ingredient', '0006_favouriteingredient_deleted_allergicingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsuggestion',
            name='attachment',
            field=models.ForeignKey(blank=True, db_column='attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_suggestion_fk_attachment', to='attachment.attachment'),
        ),
    ]
