# Generated by Django 5.2.1 on 2026-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0007_ingredientsuggestion_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='source',
            field=models.CharField(choices=[('CHEF_SUGGESTION', 'Chef Suggestion'), ('USDA', 'USDA Database')], default='USDA', max_length=15),
        ),
    ]
