# Generated by Django 5.2.1 on 2026-05-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0008_ingredient_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsuggestion',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
