# Generated by Django 5.2.1 on 2026-01-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_address',
            field=models.ForeignKey(blank=True, db_column='delivery_address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_fk_delivery_address', to='profile.customeraddress'),
        ),
    ]
