# Generated by Django 5.2.1 on 2026-01-20 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0002_initial'),
        ('order', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_fk_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(db_column='checkout_uid', on_delete=django.db.models.deletion.CASCADE, related_name='order_fk_checkout', to='order.checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(blank=True, db_column='chef_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_fk_chef', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_fk_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, db_column='dish_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem_fk_dish', to='dish.dish'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='order_uid', on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_fk_order', to='order.order'),
        ),
    ]
