# Generated by Django 5.2.1 on 2026-01-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('PAYOS', 'PayOS')], default='COD', max_length=16),
        ),
    ]
