# Generated by Django 5.2.1 on 2026-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_checkout_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED_SYSTEM', 'Confirmed by System'), ('CONFIRMED_SHOP', 'Confirmed by Shop'), ('PROCESSING', 'Processing'), ('DELIVERING', 'Delivering'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
    ]
