# Generated by Django 5.2.1 on 2026-02-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số tiền giảm từ voucher', max_digits=12),
        ),
    ]
