# Generated by Django 5.2.1 on 2026-02-25 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_discount_amount'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, db_column='voucher_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_fk_voucher', to='voucher.voucher'),
        ),
    ]
