# Generated by Django 5.2.1 on 2026-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='voucher',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng số tiền giảm giá (platform + shop vouchers) - tính từ AppliedVoucher', max_digits=12),
        ),
    ]
