# Generated by Django 5.2.1 on 2026-03-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_voucher_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='platform_shipping_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giảm giá từ platform shipping voucher (allocated proportionally)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_subtotal_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giảm giá từ platform subtotal voucher (allocated proportionally)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Giảm giá từ shop voucher (chef's voucher)", max_digits=12),
        ),
    ]
