# Generated by Django 5.2.1 on 2026-05-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng giảm giá (platform + shop)', max_digits=15),
        ),
    ]
