# Generated by Django 5.2.1 on 2026-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_text',
            field=models.CharField(blank=True, help_text='Chuỗi địa chỉ đầy đủ', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.FloatField(blank=True, help_text='Vĩ độ giao hàng', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.FloatField(blank=True, help_text='Kinh độ giao hàng', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, help_text='Tên người nhận lúc đặt đơn', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(blank=True, help_text='SĐT người nhận lúc đặt đơn', max_length=20, null=True),
        ),
    ]
