# Generated by Django 5.2.1 on 2026-06-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_delivery_address_text_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('SELF_PICKUP', 'Tự đến lấy'), ('THIRD_PARTY', 'Dịch vụ vận chuyển thứ 3')], default='THIRD_PARTY', help_text='Phương thức giao hàng của đơn này', max_length=20),
        ),
    ]
