# Generated by Django 5.2.1 on 2026-04-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='fcm_token',
            field=models.CharField(max_length=255),
        ),
    ]
