# Generated by Django 5.2.1 on 2026-04-26 07:51

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFoodPreferenceFeature',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergic_ingredient_ids', models.JSONField(blank=True, default=list)),
                ('diet_mode', models.CharField(choices=[('NONE', 'None'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('KETO', 'Keto'), ('PALEO', 'Paleo')], default='NONE', max_length=16)),
                ('diet_level', models.CharField(choices=[('NONE', 'None'), ('STRICT', 'Strict'), ('MODERATE', 'Moderate'), ('FLEXIBLE', 'Flexible')], default='NONE', max_length=16)),
                ('allergy_mode', models.CharField(choices=[('WARN', 'Warn'), ('HIDE', 'Hide')], default='WARN', max_length=16)),
                ('favorite_ingredient_ids', models.JSONField(blank=True, default=list)),
                ('favorite_dish_ids', models.JSONField(blank=True, default=list)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_food_preference_feature_fk_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_food_preference_feature',
            },
        ),
    ]
