# Generated by Django 5.2.1 on 2026-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodpreferencefeature',
            name='diet_level',
            field=models.CharField(choices=[('NONE', 'None'), ('SOFT', 'Soft Influence'), ('MEDIUM', 'Medium Influence'), ('STRONG', 'Strong Influence')], default='NONE', max_length=16),
        ),
        migrations.AlterField(
            model_name='userfoodpreferencefeature',
            name='diet_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('BALANCED', 'Balanced'), ('LOW_CARB', 'Low Carb'), ('HIGH_PROTEIN', 'High Protein'), ('LOW_FAT', 'Low Fat'), ('LIGHT', 'Light / Healthy eating')], default='NONE', max_length=17),
        ),
    ]
