# Generated by Django 5.2.1 on 2026-04-27 00:00

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0017_dishingredient_confidence"),
        ("recommendation", "0003_pgvector_ann_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DishTranslationMapping",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vietnamese_name", models.TextField(unique=True)),
                ("normalized_vietnamese_name", models.TextField(db_index=True)),
                ("english_name", models.TextField(blank=True, null=True)),
                ("ingredients", models.JSONField(blank=True, default=list)),
                ("nutrition_per_serving", models.JSONField(blank=True, default=dict)),
                ("serving_grams", models.FloatField(default=100.0)),
                ("usda_confidence", models.FloatField(default=0.8)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "dish_translation_mapping",
            },
        ),
        migrations.CreateModel(
            name="UserDailyNutrition",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("age", models.PositiveIntegerField(default=25)),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                        default="OTHER",
                        max_length=8,
                    ),
                ),
                ("height_cm", models.FloatField(default=170.0)),
                ("weight_kg", models.FloatField(default=65.0)),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("SEDENTARY", "Sedentary"),
                            ("LIGHT", "Light"),
                            ("MODERATE", "Moderate"),
                            ("ACTIVE", "Active"),
                            ("VERY_ACTIVE", "Very Active"),
                        ],
                        default="LIGHT",
                        max_length=16,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[("MAINTAIN", "Maintain"), ("LOSE", "Lose"), ("GAIN", "Gain")],
                        default="MAINTAIN",
                        max_length=16,
                    ),
                ),
                ("bmr_kcal", models.FloatField(default=0.0)),
                ("tdee_kcal", models.FloatField(default=0.0)),
                ("target_protein_g", models.FloatField(default=0.0)),
                ("target_lipid_g", models.FloatField(default=0.0)),
                ("target_carb_g", models.FloatField(default=0.0)),
                ("target_sodium_mg", models.FloatField(default=0.0)),
                ("target_fiber_g", models.FloatField(default=0.0)),
                ("consumed_protein_g", models.FloatField(default=0.0)),
                ("consumed_lipid_g", models.FloatField(default=0.0)),
                ("consumed_carb_g", models.FloatField(default=0.0)),
                ("consumed_sodium_mg", models.FloatField(default=0.0)),
                ("consumed_fiber_g", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_daily_nutrition_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_daily_nutrition",
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="DailyMealLog",
            fields=[
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("APP", "App"), ("PARSED", "Parsed"), ("USDA", "USDA"), ("MANUAL", "Manual")],
                        default="PARSED",
                        max_length=16,
                    ),
                ),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast"),
                            ("LUNCH", "Lunch"),
                            ("DINNER", "Dinner"),
                            ("SNACK", "Snack"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("meal_name", models.TextField()),
                ("quantity_multiplier", models.FloatField(default=1.0)),
                ("nutrition_protein_g", models.FloatField(default=0.0)),
                ("nutrition_lipid_g", models.FloatField(default=0.0)),
                ("nutrition_carb_g", models.FloatField(default=0.0)),
                ("nutrition_sodium_mg", models.FloatField(default=0.0)),
                ("nutrition_fiber_g", models.FloatField(default=0.0)),
                ("confidence_parse", models.FloatField(default=1.0)),
                ("confidence_source", models.FloatField(default=1.0)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "daily_nutrition",
                    models.ForeignKey(
                        db_column="daily_nutrition_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_meal_logs",
                        to="recommendation.userdailynutrition",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        db_column="dish_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_meal_log_fk_dish",
                        to="dish.dish",
                    ),
                ),
            ],
            options={
                "db_table": "daily_meal_log",
            },
        ),
    ]
