# Generated by Django 5.2.1 on 2026-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_daily_nutrition_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailynutrition',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], default='OTHER', max_length=16),
        ),
        migrations.AlterField(
            model_name='userdailynutrition',
            name='goal',
            field=models.CharField(choices=[('MAINTAIN', 'Maintain Weight'), ('LOSE', 'Lose Weight'), ('GAIN', 'Gain Weight')], default='MAINTAIN', max_length=16),
        ),
    ]
