# Generated by Django 5.2.1 on 2026-05-05 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_daily_meal_log_user_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishRecipeSnapshot',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish_name', models.TextField()),
                ('normalized_name', models.TextField(db_index=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='GEMINI', max_length=32)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'dish_recipe_snapshot',
            },
        ),
    ]
