# Generated by Django 5.2.1 on 2026-03-11 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0004_alter_attachment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('issued_by', models.TextField()),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certificate_type', models.CharField(choices=[('FOOD_SAFETY', 'Food Safety Certificate'), ('BUSINESS_LICENSE', 'Business License')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('name_no_accent', models.TextField(blank=True, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('attachment', models.ForeignKey(blank=True, db_column='attachment_uid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_fk_attachment', to='attachment.attachment')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_fk_owner', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_fk_verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
