# Generated by Django 5.2.1 on 2026-03-31 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0005_alter_attachment_type'),
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='attachment',
        ),
        migrations.CreateModel(
            name='CertificateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('attachment', models.ForeignKey(db_column='attachment_uid', on_delete=django.db.models.deletion.CASCADE, related_name='certificateattachment_fk_attachment', to='attachment.attachment')),
                ('certificate', models.ForeignKey(db_column='certificate_uid', on_delete=django.db.models.deletion.CASCADE, related_name='attachment_fk_certificate', to='certificate.certificate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('certificate', 'attachment'), name='unique_certificate_attachment'), models.UniqueConstraint(fields=('certificate', 'position'), name='unique_certificate_position')],
            },
        ),
    ]
