# Generated by Django 5.2.1 on 2026-03-13 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_fk_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_column='verified_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_fk_verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
