# Generated by Django 5.2.1 on 2026-05-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_initial'),
        ('certificate', '0002_remove_certificate_attachment_certificateattachment'),
    ]

    operations = [
    ]
