# Generated by Django 5.2.1 on 2026-03-13 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0002_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='chef',
            field=models.ForeignKey(blank=True, db_column='chef_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_fk_chef', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='updater',
            field=models.ForeignKey(blank=True, db_column='updater_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_fk_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menudish',
            name='dish',
            field=models.ForeignKey(blank=True, db_column='dish_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menudish_fk_dish', to='dish.dish'),
        ),
        migrations.AddField(
            model_name='menudish',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='menudish_fk_menu', to='menu.menu'),
        ),
        migrations.AlterUniqueTogether(
            name='menudish',
            unique_together={('menu', 'dish')},
        ),
    ]
