# Generated by Django 5.2.1 on 2026-03-11 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0005_alter_attachment_type'),
        ('dish', '0004_dish_avg_rating'),
        ('order', '0009_remove_order_discount_amount_and_more'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(help_text='Rating từ 1-5 sao', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('attachment', models.ForeignKey(blank=True, db_column='attachment_uid', help_text='Hình ảnh đính kèm review (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_fk_attachment', to='attachment.attachment')),
                ('dish', models.ForeignKey(db_column='dish_uid', on_delete=django.db.models.deletion.CASCADE, related_name='review_fk_dish', to='dish.dish')),
                ('order', models.ForeignKey(blank=True, db_column='order_uid', help_text='Order mà user đã mua món này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_fk_order', to='order.order')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_fk_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'dish', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Nội dung reply của chef')),
                ('deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', help_text='Chef reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reply_fk_owner', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(db_column='review_uid', help_text='Review được reply', on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='review.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
