# Generated by Django 5.2.1 on 2026-03-13 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_fk_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', help_text='Chef reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reply_fk_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='review',
            field=models.OneToOneField(db_column='review_uid', help_text='Review được reply', on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='review.review'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'dish', 'order')},
        ),
    ]
