# Generated by Django 5.2.1 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_reviewreply_delete_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
