# Generated by Django 5.2.1 on 2026-05-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
        ('review', '0003_review_issue_review_weight'),
    ]

    operations = [
    ]
