# Generated by Django 5.2.1 on 2026-01-20 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('VNPAY', 'VNPay')], default='COD', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vnp_txn_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('vnp_transaction_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vnp_bank_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vnp_card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='order.checkout')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payment_tra_transac_4a22d3_idx'), models.Index(fields=['vnp_txn_ref'], name='payment_tra_vnp_txn_b144fa_idx'), models.Index(fields=['status'], name='payment_tra_status_137fde_idx')],
            },
        ),
    ]
