# Generated by Django 5.2.1 on 2026-01-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_checkout_payment_method'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payos_order_code',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payos_payment_link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('PAYOS', 'PayOS')], default='COD', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payos_order_code'], name='payment_tra_payos_o_a4722d_idx'),
        ),
    ]
