# Generated by Django 5.2.1 on 2026-05-01 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_discount_amount_and_more'),
        ('payment', '0002_paymenttransaction_payos_order_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefCODBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsettled_balance', models.DecimalField(decimal_places=2, default=0, help_text='Total COD money collected but not yet settled', max_digits=15)),
                ('unsettled_orders_count', models.IntegerField(default=0, help_text='Number of COD orders awaiting settlement')),
                ('total_settled', models.DecimalField(decimal_places=2, default=0, help_text='Total COD money settled to chef', max_digits=15)),
                ('last_settlement_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cod_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chef_cod_balance',
            },
        ),
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('chef_payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LEDGER_RECORDED', 'Ledger Recorded'), ('PAYOUT_SCHEDULED', 'Payout Scheduled'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('PAYOS', 'PayOS')], default='COD', max_length=20)),
                ('payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('settlement_data', models.JSONField(blank=True, null=True)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_records', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_record', to='order.order')),
            ],
            options={
                'db_table': 'settlement_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ledger_type', models.CharField(choices=[('CHEF_PAYOUT', 'Chef Payout'), ('PLATFORM_REVENUE', 'Platform Revenue'), ('PAYOUT_REVERSAL', 'Payout Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('order_uid', models.CharField(max_length=100)),
                ('chef_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='payment.settlementrecord')),
            ],
            options={
                'db_table': 'payout_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='settlementrecord',
            index=models.Index(fields=['chef', 'status'], name='settlement__chef_id_723f55_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementrecord',
            index=models.Index(fields=['payment_method', 'status'], name='settlement__payment_6bc666_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementrecord',
            index=models.Index(fields=['created_at'], name='settlement__created_3e729d_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutledger',
            index=models.Index(fields=['ledger_type', 'created_at'], name='payout_ledg_ledger__1ad9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutledger',
            index=models.Index(fields=['chef_id', 'created_at'], name='payout_ledg_chef_id_ba4ced_idx'),
        ),
    ]
