# Generated by Copilot on 2026-05-03

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_chefcodbalance_settlementrecord_payoutledger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_remove_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('RETRYING', 'Retrying'), ('DEAD', 'Dead'), ('NEEDS_MANUAL_FIX', 'Needs Manual Fix'), ('NEEDS_CHEF_UPDATE_BANK', 'Needs Chef Update Bank')], default='QUEUED', max_length=30)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_job', to='payment.settlementrecord')),
            ],
            options={
                'db_table': 'payout_jobs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='settlementrecord',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYOUT', 'Pending Payout'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('NEEDS_MANUAL_FIX', 'Needs Manual Fix'), ('NEEDS_CHEF_UPDATE_BANK', 'Needs Chef Update Bank'), ('LEDGER_RECORDED', 'Ledger Recorded'), ('PAYOUT_SCHEDULED', 'Payout Scheduled'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed')], default='PENDING_PAYOUT', max_length=30),
        ),
        migrations.AddIndex(
            model_name='payoutjob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='payout_job_status_5d5c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutjob',
            index=models.Index(fields=['created_at'], name='payout_job_created_4b0ef1_idx'),
        ),
    ]
