# Generated by Django 5.2.1 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payoutjob_settlement_pending_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LEDGER_RECORDED', 'Ledger Recorded'), ('PAYOUT_SCHEDULED', 'Payout Scheduled'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='PayoutJob',
        ),
    ]
