# Generated by Django 5.2.1 on 2026-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_settlement_retry_safety_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='settlementrecord',
            name='settlement_r_retry_l_fbb95f_idx',
        ),
        migrations.RemoveField(
            model_name='settlementrecord',
            name='last_retry_at',
        ),
        migrations.RemoveField(
            model_name='settlementrecord',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='settlementrecord',
            name='retry_lock',
        ),
        migrations.AlterField(
            model_name='settlementrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LEDGER_RECORDED', 'Ledger Recorded'), ('PAYOUT_SCHEDULED', 'Payout Scheduled'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed')], default='PENDING', max_length=20),
        ),
    ]
