# Generated by Django 5.2.1 on 2026-05-07 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_payment_status'),
        ('payment', '0007_remove_settlementrecord_settlement_r_retry_l_fbb95f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('HOLDING', 'Holding'), ('SUCCESS', 'Success'), ('RELEASED', 'Released'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=20)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Payment Information',
                'verbose_name_plural': 'Customer Payment Information',
                'db_table': 'customer_payment_info',
            },
        ),
        migrations.CreateModel(
            name='InternalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('HOLD', 'Hold'), ('RELEASE', 'Release'), ('REFUND', 'Refund'), ('PAYOUT', 'Payout')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_id', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payout_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='wallet_tran_user_id_5cf180_idx'), models.Index(fields=['transaction_type', 'status'], name='wallet_tran_transac_dcb2c5_idx')],
            },
        ),
    ]
