# Generated by Django 5.2.1 on 2026-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymenttransaction_status_customerpaymentinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('HOLDING', 'Holding'), ('RELEASED', 'Released'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('HOLD', 'Hold'), ('RELEASE', 'Release from escrow'), ('REFUND', 'Refund to customer'), ('PAYOUT', 'Payout to chef')], max_length=20),
        ),
    ]
