# Generated by Django 5.2.1 on 2026-05-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_wallet_transaction_immutable_trigger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='withdrawalfailurelog',
            new_name='wallet_with_user_id_a9a234_idx',
            old_name='wallet_with_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalfailurelog',
            new_name='wallet_with_stage_c0ac17_idx',
            old_name='wallet_with_stage_idx',
        ),
    ]
