# Generated by GitHub Copilot on 2026-05-17

from django.db import migrations, models
import django.db.models.deletion


def _backfill_wallet_transaction_state(apps, schema_editor):
    WalletTransaction = apps.get_model("payment", "WalletTransaction")
    WalletTransactionState = apps.get_model("payment", "WalletTransactionState")

    batch = []
    batch_size = 500

    existing_ids = set(
        WalletTransactionState.objects.values_list("wallet_transaction_id", flat=True)
    )

    for tx in WalletTransaction.objects.all().iterator():
        if tx.id in existing_ids:
            continue
        batch.append(
            WalletTransactionState(
                wallet_transaction_id=tx.id,
                status=tx.status,
                description=tx.description or "",
                metadata=tx.metadata,
                payout_id=tx.payout_id,
                processed_at=tx.processed_at,
                created_at=tx.created_at,
                updated_at=tx.processed_at or tx.created_at,
            )
        )
        if len(batch) >= batch_size:
            WalletTransactionState.objects.bulk_create(batch, batch_size=batch_size)
            batch = []

    if batch:
        WalletTransactionState.objects.bulk_create(batch, batch_size=batch_size)


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_wallet_transaction_immutable_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransactionState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("payout_id", models.CharField(blank=True, max_length=120, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="payment.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transaction_states",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(_backfill_wallet_transaction_state, migrations.RunPython.noop),
        migrations.RemoveField(model_name="wallettransaction", name="status"),
        migrations.RemoveField(model_name="wallettransaction", name="description"),
        migrations.RemoveField(model_name="wallettransaction", name="metadata"),
        migrations.RemoveField(model_name="wallettransaction", name="payout_id"),
        migrations.RemoveField(model_name="wallettransaction", name="processed_at"),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["transaction_type"], name="wallet_tx_type_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransactionstate",
            index=models.Index(fields=["status"], name="wallet_tx_state_status_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransactionstate",
            index=models.Index(fields=["processed_at"], name="wallet_tx_state_processed_idx"),
        ),
    ]
