# Generated by GitHub Copilot on 2026-05-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0013_rename_wallet_with_user_id_idx_wallet_with_user_id_a9a234_idx_and_more"),
        ("payment", "0013_wallet_transaction_state"),
    ]

    operations = [
    ]
