# Generated by GitHub Copilot on 2026-05-17

from django.db import migrations, models
import django.db.models.deletion
import hashlib
import hmac


def _payment_event_hmac(msg: str, secret: str) -> str:
    return hmac.new(secret.encode(), msg.encode(), hashlib.sha256).hexdigest()


def _backfill_payment_state_and_events(apps, schema_editor):
    PaymentTransaction = apps.get_model("payment", "PaymentTransaction")
    PaymentTransactionState = apps.get_model("payment", "PaymentTransactionState")
    PaymentTransactionEvent = apps.get_model("payment", "PaymentTransactionEvent")
    try:
        from django.conf import settings as django_settings
        secret = getattr(django_settings, "PAYMENT_EVENT_SECRET", django_settings.SECRET_KEY)
    except Exception:
        secret = ""

    existing_state_ids = set(
        PaymentTransactionState.objects.values_list("payment_transaction_id", flat=True)
    )

    for payment in PaymentTransaction.objects.all().iterator():
        if payment.id in existing_state_ids:
            continue
        state = PaymentTransactionState.objects.create(
            payment_transaction_id=payment.id,
            status=getattr(payment, "status", "PENDING"),
            paid_at=getattr(payment, "paid_at", None),
            gateway_response=getattr(payment, "gateway_response", None),
            created_at=payment.created_at,
            updated_at=getattr(payment, "updated_at", payment.created_at),
        )

        previous_hash = "0" * 64
        chain_hash = _payment_event_hmac(
            f"{payment.id}:BACKFILL:None:{state.status}:{previous_hash}",
            secret,
        )
        PaymentTransactionEvent.objects.create(
            payment_transaction_id=payment.id,
            event_type="BACKFILL",
            status_from=None,
            status_to=state.status,
            payload=state.gateway_response,
            signature_valid=None,
            source="migration",
            previous_hash=previous_hash,
            chain_hash=chain_hash,
        )


def _noop(apps, schema_editor):
    pass


_CREATE_FUNCTION = """
CREATE OR REPLACE FUNCTION prevent_payment_transaction_modification()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'payment_transactions is append-only: UPDATE and DELETE are not permitted';
END;
$$ LANGUAGE plpgsql;
"""

_CREATE_UPDATE_TRIGGER = """
CREATE TRIGGER no_payment_transaction_update
BEFORE UPDATE ON payment_transactions
FOR EACH ROW EXECUTE FUNCTION prevent_payment_transaction_modification();
"""

_CREATE_DELETE_TRIGGER = """
CREATE TRIGGER no_payment_transaction_delete
BEFORE DELETE ON payment_transactions
FOR EACH ROW EXECUTE FUNCTION prevent_payment_transaction_modification();
"""

_DROP_TRIGGERS = """
DROP TRIGGER IF EXISTS no_payment_transaction_update ON payment_transactions;
DROP TRIGGER IF EXISTS no_payment_transaction_delete ON payment_transactions;
DROP FUNCTION IF EXISTS prevent_payment_transaction_modification();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0014_merge_0013_wallet_transaction_state_and_rename_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransactionState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("HOLDING", "Holding"),
                            ("RELEASED", "Released"),
                            ("REFUND_PENDING", "Refund pending"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payment_transaction_states",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransactionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=40)),
                ("status_from", models.CharField(blank=True, max_length=20, null=True)),
                ("status_to", models.CharField(blank=True, max_length=20, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("signature_valid", models.BooleanField(blank=True, null=True)),
                ("source", models.CharField(blank=True, default="", max_length=40)),
                ("previous_hash", models.CharField(default="0" * 64, max_length=64)),
                ("chain_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payment_transaction_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(_backfill_payment_state_and_events, _noop),
        migrations.RemoveField(model_name="paymenttransaction", name="status"),
        migrations.RemoveField(model_name="paymenttransaction", name="paid_at"),
        migrations.RemoveField(model_name="paymenttransaction", name="gateway_response"),
        migrations.RemoveField(model_name="paymenttransaction", name="updated_at"),
        migrations.AddIndex(
            model_name="paymenttransactionstate",
            index=models.Index(fields=["status"], name="payment_tx_state_status_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransactionstate",
            index=models.Index(fields=["paid_at"], name="payment_tx_state_paid_at_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransactionevent",
            index=models.Index(fields=["payment_transaction", "created_at"], name="payment_tx_event_tx_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransactionevent",
            index=models.Index(fields=["event_type"], name="payment_tx_event_type_idx"),
        ),
        migrations.RunSQL(
            sql=_CREATE_FUNCTION + _CREATE_UPDATE_TRIGGER + _CREATE_DELETE_TRIGGER,
            reverse_sql=_DROP_TRIGGERS,
        ),
    ]
