# Generated by Django 5.2.1 on 2026-05-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_payment_transaction_state_events'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_tra_transac_4a22d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_tra_status_137fde_idx',
        ),
        migrations.RemoveIndex(
            model_name='wallettransaction',
            name='wallet_tran_transac_dcb2c5_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_url',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payos_payment_link_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='paymenttransactionstate',
            name='payment_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransactionstate',
            name='payos_payment_link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransactionstate',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
