# Generated by Django 5.2.1 on 2026-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotp_target_email_and_purpose_email_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='purpose',
            field=models.CharField(choices=[('SIGNUP', 'Sign Up'), ('RESET_PASSWORD', 'Reset Password'), ('EMAIL_CHANGE', 'Email Change'), ('BANK_VERIFY', 'Bank Account Verify'), ('WITHDRAW_VERIFY', 'Withdraw Verify')], max_length=16),
        ),
    ]
