# Generated by Django 5.2.1 on 2026-05-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userotp_otp_hash_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_hash',
            field=models.TextField(),
        ),
    ]
