# Generated by GitHub Copilot on 2026-05-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userotp_otp_hash"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'users_userotp'
                      AND column_name = 'otp_salt'
                ) THEN
                    ALTER TABLE users_userotp DROP COLUMN otp_salt;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'users_userotp'
                      AND column_name = 'otp_salt'
                ) THEN
                    ALTER TABLE users_userotp ADD COLUMN otp_salt varchar(255);
                END IF;
            END $$;
            """,
        ),
    ]
