# Generated by Django 5.2.1 on 2026-05-18 11:32

import hashlib
import hmac
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now


def _hash_refresh_token(raw_token: str) -> str:
    pepper = (getattr(settings, "AUTH_REFRESH_TOKEN_PEPPER", None) or settings.SECRET_KEY).encode()
    return hmac.new(pepper, raw_token.encode(), hashlib.sha256).hexdigest()


def backfill_auth_tokens(apps, schema_editor):
    AuthenticateToken = apps.get_model("users", "AuthenticateToken")
    for record in AuthenticateToken.objects.all().iterator():
        update_fields = []

        # Always rewrite jti to guarantee uniqueness before unique constraint.
        record.jti = uuid.uuid4()
        update_fields.append("jti")

        if not record.token_hash:
            raw_token = getattr(record, "token", None)
            if raw_token:
                record.token_hash = _hash_refresh_token(raw_token)
            else:
                record.token_hash = _hash_refresh_token(str(uuid.uuid4()))
            update_fields.append("token_hash")

        if record.expires_at is None:
            record.expires_at = now()
            update_fields.append("expires_at")

        if update_fields:
            record.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_drop_userotp_otp_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticatetoken',
            old_name='blacklisted_at',
            new_name='revoked_at',
        ),
        migrations.AddField(
            model_name='authenticatetoken',
            name='jti',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.AddField(
            model_name='authenticatetoken',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='users.authenticatetoken'),
        ),
        migrations.AddField(
            model_name='authenticatetoken',
            name='token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(backfill_auth_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='authenticatetoken',
            name='jti',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='authenticatetoken',
            name='token',
        ),
        migrations.AlterField(
            model_name='authenticatetoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
