# Generated by Django 5.2.1 on 2026-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_blacklisted_at_authenticatetoken_revoked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatetoken',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
