# Generated by Django 5.2.1 on 2026-06-03 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_authenticatetoken_token_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticatetoken',
            name='replaced_by',
        ),
        migrations.RemoveField(
            model_name='authenticatetoken',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='authenticatetoken',
            name='token_hash',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authenticatetoken',
            name='jti',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='authenticatetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticate_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authenticatetoken',
            index=models.Index(fields=['user', 'revoked_at'], name='users_authe_user_id_84a765_idx'),
        ),
    ]
