# Generated by Django 5.2.1 on 2026-01-27 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_alter_attachment_type'),
        ('profile', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefprofile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='file',
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, db_column='attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_profile_fk_attachment', to='attachment.attachment'),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='specialty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, db_column='attachment_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile_fk_attachment', to='attachment.attachment'),
        ),
        migrations.CreateModel(
            name='ChefPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Tên ngân hàng (VD: Vietcombank, VPBank)', max_length=255)),
                ('bank_account_number', models.CharField(help_text='Số tài khoản ngân hàng', max_length=50)),
                ('bank_account_name', models.CharField(help_text='Tên chủ tài khoản', max_length=255)),
                ('bank_branch', models.CharField(blank=True, help_text='Chi nhánh (optional)', max_length=255, null=True)),
                ('citizen_id', models.CharField(blank=True, help_text='CCCD/CMND', max_length=20, null=True)),
                ('tax_code', models.CharField(blank=True, help_text='Mã số thuế (nếu có)', max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Đã xác thực thông tin chưa')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_payment_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef Payment Information',
                'verbose_name_plural': 'Chef Payment Information',
                'db_table': 'chef_payment_info',
            },
        ),
    ]
