# Generated by Django 5.2.1 on 2026-04-25 14:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0007_alter_attachment_type'),
        ('profile', '0004_add_bank_code_to_chefpaymentinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='allergy_mode',
            field=models.CharField(choices=[('WARN', 'Warn'), ('HIDE', 'Hide')], default='WARN', max_length=16),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='diet_level',
            field=models.CharField(choices=[('NONE', 'None'), ('STRICT', 'Strict'), ('MODERATE', 'Moderate'), ('FLEXIBLE', 'Flexible')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='diet_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('KETO', 'Keto'), ('PALEO', 'Paleo')], default='NONE', max_length=16),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diet_level', 'NONE'), ('diet_mode', 'NONE')), models.Q(('diet_mode', 'NONE'), _negated=True), _connector='OR'), name='diet_level_none_when_mode_none'),
        ),
    ]
