# Generated by Django 5.2.1 on 2026-04-26 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0007_alter_attachment_type'),
        ('dish', '0016_alter_dishingredient_approval_status_and_more'),
        ('profile', '0005_customerprofile_allergy_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFavoriteDish',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='customerprofile',
            name='diet_level_none_when_mode_none',
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diet_level', 'NONE'), ('diet_mode', 'NONE')), models.Q(models.Q(('diet_mode', 'NONE'), _negated=True), models.Q(('diet_level', 'NONE'), _negated=True)), _connector='OR'), name='diet_mode_level_consistency'),
        ),
        migrations.AddField(
            model_name='customerfavoritedish',
            name='dish',
            field=models.ForeignKey(db_column='dish_uid', on_delete=django.db.models.deletion.CASCADE, related_name='customer_favorite_dish_fk_dish', to='dish.dish'),
        ),
        migrations.AddField(
            model_name='customerfavoritedish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_favorite_dish_user_fk_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customerfavoritedish',
            unique_together={('user', 'dish')},
        ),
    ]
