# Generated by Django 5.2.1 on 2026-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_customerfavoritedish_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefpaymentinfo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
