# Generated by Django 5.2.1 on 2026-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_chefpaymentinfo_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
