# Generated by Django 5.2.1 on 2026-05-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_chefpaymentinfo_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
