# Generated by Django 5.2.1 on 2026-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_customeraddress_latitude_customeraddress_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_address',
            field=models.CharField(blank=True, help_text='Số nhà, Tên tòa nhà', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
