# Generated by Django 5.2.1 on 2026-05-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_customeraddress_deleted'),
        ('profile', '0010_chefprofile_kitchen_address_chefprofile_kitchen_city_and_more'),
    ]

    operations = [
    ]
