# Generated by Django 5.2.1 on 2026-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_merge_20260514_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='suspension_level',
            field=models.CharField(choices=[('NONE', 'Bình thường'), ('WARNING', 'Cảnh báo'), ('SUSPENDED', 'Đã khóa')], default='NONE', max_length=16),
        ),
    ]
