# Generated by Django 5.2.1 on 2026-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_merge_20260514_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
